### ISSUE TITLE
Stucked ResQU jobs La_WorkReport_ProcessUserSlotReportJob

### ISSUE THREAD

**Issue by LHozzan** [QualityUnit/resqu-server#3] opened 2020-05-13 13:16 UTC
**Describe the bug**
In maintenance I found some stucked workers:
```
|7|[root@1.app-q.la.ws-eu ~]$ ps aux | grep resqu-v5-
root      3298  0.0  0.0 492948 11384 ?        S    07:50   0:00 resqu-v5-11602-std-proc: Processing job La_WorkReport_ProcessUserSlotReportJob
root      3308  0.0  0.0 492948 11436 ?        S    07:50   0:00 resqu-v5-11601-std-proc: Processing job La_WorkReport_ProcessUserSlotReportJob
root     11601  0.1  0.0 490900  5568 ?        S    máj03  24:12 resqu-v5-w-default_job_pool-s: Forked 3308 at 2020-05-13 00:50:14
root     11602  0.1  0.0 490900  5668 ?        S    máj03  24:08 resqu-v5-w-default_job_pool-s: Forked 3298 at 2020-05-13 00:50:14
```
It seems, that only exist and nothing to do.

Sending SIGTERM not have any effect:
```
|7|[root@1.app-q.la.ws-eu ~]$ kill 3298 3308
|7|[root@1.app-q.la.ws-eu ~]$ ps aux | grep resqu-v5-
root      3298  0.0  0.0 492948 11384 ?        S    07:50   0:00 resqu-v5-11602-std-proc: Processing job La_WorkReport_ProcessUserSlotReportJob
root      3308  0.0  0.0 492948 11436 ?        S    07:50   0:00 resqu-v5-11601-std-proc: Processing job La_WorkReport_ProcessUserSlotReportJob
root     11601  0.1  0.0 490900  5568 ?        S    máj03  24:12 resqu-v5-w-default_job_pool-s: Forked 3308 at 2020-05-13 00:50:14
root     11602  0.1  0.0 490900  5668 ?        S    máj03  24:08 resqu-v5-w-default_job_pool-s: Forked 3298 at 2020-05-13 00:50:14
```

Force killing was successfull:
```
|7|[root@1.app-q.la.ws-eu ~]$ kill 3298 3308
|7|[root@1.app-q.la.ws-eu ~]$ ps aux | grep resqu-v5-
root      3298  0.0  0.0 492948 11384 ?        S    07:50   0:00 resqu-v5-11602-std-proc: Processing job La_WorkReport_ProcessUserSlotReportJob
root      3308  0.0  0.0 492948 11436 ?        S    07:50   0:00 resqu-v5-11601-std-proc: Processing job La_WorkReport_ProcessUserSlotReportJob
root     11601  0.1  0.0 490900  5568 ?        S    máj03  24:12 resqu-v5-w-default_job_pool-s: Forked 3308 at 2020-05-13 00:50:14
root     11602  0.1  0.0 490900  5668 ?        S    máj03  24:08 resqu-v5-w-default_job_pool-s: Forked 3298 at 2020-05-13 00:50:14
root     28504  0.0  0.0 112736   964 pts/0    S+   09:39   0:00 grep --color=auto resqu-v5-
|7|[root@1.app-q.la.ws-eu ~]$ kill -9 3298 3308
|7|[root@1.app-q.la.ws-eu ~]$ ps aux | grep resqu-v5-
root     11601  0.1  0.0 186312  6528 ?        R    máj03  24:12 resqu-v5-w-default_job_pool-s: Shutting down
root     11602  0.1  0.0 359828  6660 ?        R    máj03  24:08 resqu-v5-w-default_job_pool-s: Shutting down
root     28576  0.0  0.0 112736   964 pts/0    S+   09:39   0:00 grep --color=auto resqu-v5-
|7|[root@1.app-q.la.ws-eu ~]$ ps aux | grep resqu-v5-
root     28604  0.0  0.0 112732   964 pts/0    S+   09:39   0:00 grep --color=auto resqu-v5-
```

**Expected behavior**
All ResQU 5 threads shutdown correctly without any killing.

**Comment by dmolnarqu** [comment] 2020-05-14 09:00
Unless there's more information about this, there's no reason to believe the issue is caused by resqu.
The fact that stuck workers were performing the same type of task suggests that the issue may lie on the side of job implementation - LiveAgent.
It should be reported as a LiveAgent issue. I will close this for now.

**Closed by dmolnarqu** 2020-05-14 09:00 UTC
